language: android
android:
  components:
    - build-tools-22.0.1
    - android-22

before_script:
  - echo no | android create avd --force -n test -t android-8 
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: "./gradlew build connectedCheck"
